Clarify how to go about assessing or trialing a new technology
ovotech/ovo-com-tech-radar pull request #4
Opened 2021-07-06 12:40 UTC by mwz

2021-07-06 13:08 UTC, brad-allan-ovo reviewed
I would prefer that technology governance and the introduction of it (effectively) is shared in a live forum where Q&A can happen and in the end we as a tech org commit to the governance.

2021-07-06 13:08 UTC, brad-allan-ovo commented on README.md
>  The OVO.com Technology Radar is a living document that attempts to capture and
```suggestion
The OVO.com Technology Radar is a living document that captures and
```

2021-07-06 13:08 UTC, brad-allan-ovo commented on README.md
> +give a high-level overview of our technology landscape.
```suggestion
provides a high-level overview of our technology landscape.
```

2021-07-06 13:09 UTC, lsale requested changes
I'd recommend we slightly modify the README for simplicity so we can highlight certain sections. For example, I'd add the following:
*Why should you use the radar?* - you cover it but it's in a paragraph. I'd make it a different section

*Why do I see adopt only* - I don't think we cover that

*What to do if my technology is not listed here* - I'd make this a different section

*What to do if my technology is listed in adopt* - I think we need a bit of guidance around this. Whilst adopt means "go ahead, choose it" we also need to explain that it's good practice to talk to other teams using that technology to understand how they use it. So design/architect first by talking to other teams

2021-07-07 09:54 UTC, mwz commented
Hi @lsale, I've addressed your feedback - I've captured those points in a FAQ section because they were all questions, but let me know if you'd prefer to have those as standalone sections in the readme.

2021-07-07 10:07 UTC, lsale approved these changes
Looks great!

2021-07-07 10:13 UTC, merged